<?php

namespace common\models;

use Yii;
use yii\base\Exception;

/**
 * This is the model class for table "item_options".
 *
 * @property int $id
 * @property string $title
 * @property string $description
 * @property int $type
 * @property ItemOptionCategories[] $categories
 * @property int $measure_id
 * @property string $default_value
 * @property int $required
 */
class ItemOption extends BaseModel
{

    const TYPE_STRING = 'string';
    const TYPE_INT = 'integer';
    const TYPE_DECIMAL = 'decimal';

    /**
     * @return array
     */
    public function getTypes()
    {
        return [
            self::TYPE_INT,
            self::TYPE_DECIMAL,
            self::TYPE_STRING,
        ];
    }

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'item_options';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['title', 'measure_id'], 'required'],
            [['measure_id'], 'integer'],
            [['title', 'description', 'default_value', 'type'], 'string', 'max' => 255],
            [['required'], 'string', 'max' => 1],
            [['categories'], 'safe'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'title' => Yii::t('app', 'Title'),
            'description' => Yii::t('app', 'Description'),
            'type' => Yii::t('app', 'Type'),
            'categories' => Yii::t('app', 'Categories'),
            'measure_id' => Yii::t('app', 'Measure'),
            'default_value' => Yii::t('app', 'Default Value'),
            'required' => Yii::t('app', 'Required'),
        ];
    }

    /**
     * @return array
     */
    public function transactions()
    {
        return [
            'default' => self::OP_ALL,
        ];
    }

    /**
     * @param bool $insert
     * @param array $changedAttributes
     * @throws Exception
     */
    public function afterSave($insert, $changedAttributes)
    {
        if ($insert) {
            foreach ($this->categories as $category) {
                $category->setAttribute('option_id', $this->id);
                if (!$category->save()) {
                    throw new Exception('Save category error');
                }
            }
        }

        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
    }

    /**
     *
     *
     * @param null $names
     * @param array $except
     * @return array
     */
    public function getAttributes($names = null, $except = [])
    {
        $attrNames = self::attributes();
        $attrNames[] = 'categories';
        $attributes = parent::getAttributes($attrNames); // TODO: Change the autogenerated stub

        return $attributes;
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCategories()
    {
        return $this->hasMany(ItemOptionCategories::class, ['option_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getMeasure()
    {
        return $this->hasone(Measure::class, ['id' => 'measure_id']);
    }

    /**
     * @param array $categories
     */
    public function setCategories($categories)
    {
        $res = [];
        if (is_array($categories)) {
            foreach ($categories as $val) {
                // will save it in afterSave
                $res[] = new ItemOptionCategories(['category_id' => $val]);
            }
        }

        $this->categories = $res;
    }

    /**
     * @return array
     */
    public function getCategoriesAsArray()
    {
        $result = [];
        /** @var ItemOptionCategories $cat */
        foreach ($this->categories as $cat) {
            $result[] = $cat->category_id;
        }

        return $result;
    }

    /**
     * @return false|int
     * @throws \Throwable
     * @throws \yii\db\StaleObjectException
     */
    public function deleteItemOption()
    {
        // delete categories from relations
        /** @var ItemOptionCategories $cat */
        foreach ($this->categories as $cat) {
            $cat->delete();
        }

        return $this->delete();
    }
}
